#ldap_setup.yml

- name: Configure LDAP Server
  hosts: ldap
  become: true
  tasks:
    - name: Install OpenLDAP
      apt:
        name: slapd
        state: present

    - name: Configure OpenLDAP
      template:
        src: templates/ldap.conf.j2
        dest: /etc/ldap/ldap.conf
      notify: Restart LDAP

    - name: Start and enable LDAP service
      service:
        name: slapd
        state: started
        enabled: true

  handlers:
    - name: Restart LDAP
      service:
        name: slapd
        state: restarted
