---
# Playbook principal pour configurer les différents services

- name: Configuration du serveur DNS
  hosts: dns
  become: true
  tasks:
    - name: Déployer le serveur DNS
      include_tasks: dns_setup.yml

- name: Configuration du serveur Active Directory
  hosts: ad
  become: true
  tasks:
    - name: Déployer le serveur Active Directory
      include_tasks: ad_setup.yml

- name: Configuration du serveur LDAP
  hosts: ldap
  become: true
  tasks:
    - name: Déployer le serveur LDAP
      include_tasks: ldap_setup.yml

- name: Configuration de Home Assistant
  hosts: home_assistant
  become: true
  tasks:
    - name: Déployer Home Assistant
      include_tasks: home_assistant_setup.yml

- name: Configuration du serveur OpenVPN
  hosts: openvpn
  become: true
  tasks:
    - name: Déployer le serveur OpenVPN
      include_tasks: openvpn_setup.yml

- name: Configuration du pare-feu OPNsense
  hosts: opnsense
  become: true
  tasks:
    - name: Déployer le pare-feu OPNsense
      include_tasks: opnsense_setup.yml

- name: Configuration de la machine client
  hosts: client
  become: true
  tasks:
    - name: Configurer la machine client
      include_tasks: client_setup.yml
