FROM ubuntu:20.04

# Met à jour les paquets et installe les dépendances nécessaires
RUN apt-get update && apt-get install -y --no-install-recommends \
    openssh-server \
    bind9 \
    samba \
    python3 \
    python3-pip \
    tzdata && \
    echo "Europe/Paris" > /etc/timezone && \
    ln -fs /usr/share/zoneinfo/Europe/Paris /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata && \
    mkdir -p /var/run/sshd && \
    echo 'root:root' | chpasswd && \
    sed -i 's/#Port 22/Port 22/' /etc/ssh/sshd_config && \
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -i 's@UsePAM yes@UsePAM no@g' /etc/ssh/sshd_config && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Installe Ansible
RUN pip3 install ansible

# Expose les ports nécessaires
EXPOSE 53/udp 53/tcp 22 139 445 389

# Commande de démarrage
CMD service ssh start && tail -f /dev/null
