FROM ubuntu:20.04

# Met à jour le système et installe OpenSSH Server
RUN apt-get update && apt-get install -y openssh-server && \
    mkdir -p /var/run/sshd && \
    echo 'root:root' | chpasswd && \
    sed -i 's/#Port 22/Port 22/' /etc/ssh/sshd_config && \
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -i 's@UsePAM yes@UsePAM no@g' /etc/ssh/sshd_config

# Expose les ports
EXPOSE 53/udp 53/tcp 22

# Commande de démarrage
CMD service ssh start && /usr/sbin/named -f
