- name: Configuration des services DNS et Samba
  hosts: all
  
  tasks:
    # Mise à jour des paquets
    - name: Mise à jour des paquets
      apt:
        update_cache: yes

    - name: Installer Bind9 et Samba
      apt:
        name:
          - bind9
          - samba
          - smbclient
          - nano
        state: present

    # Configuration de Bind9
    - name: Créer le répertoire Sysvol pour Bind
      file:
        path: /var/lib/bind/sysvol
        state: directory
        owner: root
        group: root
        mode: '0755'


    - name: Copier la configuration de Bind9
      copy:
        src: ./bind/named.conf
        dest: /etc/bind/named.conf

    - name: Copier les options de configuration de Bind9
      copy:
        src: ./bind/named.conf.options
        dest: /etc/bind/named.conf.options

    - name: Copier les fichiers de zones DNS
      copy:
        src: ./bind/zones/
        dest: /etc/bind/zones/
        # remote_src: yes
    - name: Copier les options de configuration de Samba
      copy:
        src: ./samba/smb.conf
        dest: /etc/samba/smb.conf

    - name: Redémarrer Bind9 pour appliquer les changements
      service:
        use : service
        name: named
        state: restarted

    # Configuration de Samba
    - name: Copier la configuration de Samba
      copy:
        src: ./samba/smb.conf
        dest: /etc/samba/smb.conf

    - name: Créer le répertoire Sysvol pour Samba
      file:
        path: /var/lib/samba/sysvol
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Démarrer le service Samba
      service:
        name: smdb
        state: started
        use: service

    - name: Créer un utilisateur Samba
      command: smbpasswd -a root
      args:
        creates: /etc/samba/private/smbpasswd

    # - name: Redémarrer le service Samba
    #   service:
    #     use : service
    #     name: smbd
    #     state: restarted
