- name: Configuration des services DNS et Samba
  hosts: all
  
  tasks:
    # Étape 1 : Mise à jour du système et installation des paquets nécessaires
    - name: Mise à jour des paquets
      apt:
        update_cache: yes

    - name: Installer Bind9 et Samba
      apt:
        name:
          - bind9
          - samba
        state: present

    # Étape 2 : Configuration de Bind9
    - name: Copier la configuration de Bind9
      copy:
        src: ./bind/named.conf
        dest: /etc/bind/named.conf

    # - name: Copier les fichiers de zones DNS
    #   copy:
    #     src: ./bind/zones/db.example.com
    #     dest: /var/lib/bind/db.example.com


    # Étape 3 : Configuration de Samba
    - name: Copier la configuration de Samba
      copy:
        src: ./samba/smb.conf
        dest: /etc/samba/smb.conf

    # - name: "Démarrage du service Bind9 avec service"
    #   shell: "service named start"
    #   become: true


    # - name: "activation samba"
    #   service:
    #     name: "smbd"
    #     state: "started"
    #     enabled: true
    #     use: "service"
  
