- name: Déploiement des services Bind9 et Samba
  hosts: fusion
  tasks:

    # Installation des services dans le conteneur
    - name: Installer Bind9 et Samba
      apt:
        name:
          - bind9
          - samba
        state: present
        update_cache: yes

    # Configuration de Bind9
    - name: Copier la configuration de Bind9
      copy:
        src: ./bind/named.conf
        dest: /etc/bind/named.conf

    - name: Copier les fichiers de zones Bind9
      copy:
        src: ./bind/zones/example.com.db
        dest: /var/lib/bind/example.com.db

    - name: Redémarrer Bind9
      service:
        name: bind9
        state: restarted

    # Configuration de Samba
    - name: Copier la configuration de Samba
      copy:
        src: ./samba/smb.conf
        dest: /etc/samba/smb.conf

    - name: Démarrer Samba
      service:
        name: smbd
        state: started
