- name: Configuration des services DNS et Samba
  hosts: all
  become: yes
  tasks:
    # Étape 1 : Mise à jour du système et installation des paquets nécessaires
    - name: Mise à jour des paquets
      apt:
        update_cache: yes

    - name: Installer Bind9 et Samba
      apt:
        name:
          - bind9
          - samba
        state: present

    # Étape 2 : Configuration de Bind9
    - name: Copier la configuration de Bind9
      copy:
        src: ./bind/named.conf
        dest: /etc/bind/named.conf

    - name: Copier les fichiers de zones DNS
      copy:
        src: ./bind/zones/example.com.db
        dest: /var/lib/bind/example.com.db

    - name: Redémarrer le service Bind9
      service:
        use : service
        name: named
        state: restarted

    # Étape 3 : Configuration de Samba
    - name: Copier la configuration de Samba
      copy:
        src: ./samba/smb.conf
        dest: /etc/samba/smb.conf

    - name: Redémarrer le service Samba
      service:
        name: smbd
        state: restarted
        use : service

