version: '3.8'

services:
  bind9:
    build:
      context: .
    container_name: bind9  # Nom unique du conteneur
    ports:
      - "53:53/udp"        # Port DNS UDP
      - "53:53/tcp"        # Port DNS TCP
      - "2222:22"          # Port SSH pour configuration avec Ansible
    environment:
      TZ: "Europe/Paris"   # Configuration du fuseau horaire
    networks:
      bind_network:
        ipv4_address: 192.168.0.2  # Adresse IP statique assignée
    volumes:
      - ./zones:/var/lib/bind
      - bind9_data:/etc/bind  # Données persistantes
      - type: bind
        source: ./named.conf
        target: /etc/bind/named.conf

volumes:
  bind9_data:
    driver: local           # Volume pour stocker les données persistantes

networks:
  bind_network:
    driver: bridge          # Réseau interne pour les services
    ipam:
      config:
        - subnet: 192.168.0.0/24
