version: '3.8'

services:
  vpn_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vpn
    ports:
      - "1194:1194/udp"        # Port VPN
      - "2222:22"              # Port SSH
    volumes:
      - ./openvpn:/etc/openvpn
      - ./samba:/etc/samba
      - ./kerberos:/etc/krb5.conf
    networks:
      shared_net:
        ipv4_address: 192.168.0.3
    privileged: true


networks:
  shared_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24
