version: '3.8'

services:
  vpn_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vpn
    ports:
      - "16387:16387/udp"        # Port VPN
      - "2222:22"              # Port SSH
    volumes:
      - ./openvpn:/etc/openvpn
      - ./samba:/etc/samba
      - ./kerberos:/etc/krb5.conf
      - ./ad/resolv.conf:/etc/resolv.conf
    networks:
      shared_net:
        ipv4_address: 192.168.0.3
    privileged: true


  
  home_assistant_service:
    build:
      context: ./home_assistant
      dockerfile: Dockerfile
    container_name: home_assistant
    ports:
      - "2223:22"     # SSH
      - "8123:8123" # Home Assistant Web Interface
    volumes:
      - ./samba:/etc/samba
      - ./kerberos:/etc/krb5.conf
      - ./ad/resolv.conf:/etc/resolv.conf
      - ./home_assistant/configuration.yaml:/usr/src/app/config/configuration.yaml  # Montée du fichier de config
      - ./home_assistant_system/srv/homeassistant/config:/usr/src/app/config
    networks:
      shared_net:
        ipv4_address: 192.168.0.4
    privileged: true


networks:
  shared_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24
