FROM ubuntu:20.04

# Met à jour le système et installe SSH
RUN apt-get update && apt-get install -y --no-install-recommends \
    openssh-server \
    python3 \
    python3-pip \
    nano \
    dnsutils \
    iputils-ping && \
    mkdir -p /var/run/sshd && \
    echo 'root:root' | chpasswd && \
    sed -i 's/#Port 22/Port 22/' /etc/ssh/sshd_config && \
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -i 's@UsePAM yes@UsePAM no@g' /etc/ssh/sshd_config && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Installe Ansible
RUN pip3 install ansible

# Expose les ports nécessaires
#EXPOSE 22 16387/udp 1194/udp

# Commande de démarrage
CMD service ssh start && tail -f /dev/null
