version: '3.8'

services:
  vpn_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vpn
    ports:
      - "16387:16387/udp"        # Port VPN
      - "2222:22"                # Port SSH
    volumes:
      - ./openvpn:/etc/openvpn
      # - ./samba:/etc/samba
      - ./kerberos:/etc/krb5.conf
      - ./ad/resolv.conf:/etc/resolv.conf
    networks:
      macvlan_net:
        ipv4_address: 192.168.0.10  # Adresse IP à donner au conteneur

networks:
  macvlan_net:
    external: true
