version: '3.8'

services:
  # Serveur DNS
  dns:
    build:
      context: /home/toine-fa/SAE5.02/Dockerfile/dns
    container_name: dns
    image: abilioesteves/bind9:0.0.3
    volumes:
      - data:/keys
    ports:
      - "5443:5443/udp"
      - "5553:5553/tcp"
      - "10000:10000/tcp"
      - "2222:22"  # Port SSH exposé sur l'hôte (port 2222 pour ce service)
    networks:
      internal_net:
        ipv4_address: 192.168.0.2

  # Active Directory avec Samba
  ad:
    build:
      context: /home/toine-fa/SAE5.02/Dockerfile/samba
    image: crazymax/samba
    networks:
      internal_net:
        ipv4_address: 192.168.0.3
    container_name: ad
    volumes:
      - ./smb:/data
      - ./downloads:/downloads
    environment:
      - "TZ=${TIMEZONE}"
      - "SAMBA_LOG_LEVEL=0"
    restart: always
    ports:
      - "2223:22"  # Port SSH exposé sur l'hôte (port 2223 pour ce service)

  ldap:
    build:
      context: /home/toine-fa/SAE5.02/Dockerfile/ldap_cli
    image: dnknth/ldap-ui
    container_name: ldap
    networks:
      internal_net:
        ipv4_address: 192.168.0.4
    environment:
      - LDAP_URL=ldap://ldap:1389
      - BASE_DN=dc=example,dc=org
      - BIND_PATTERN=%s
    ports:
      - "1234:5000"
      - "2224:22"  # Port SSH exposé sur l'hôte (port 2224 pour ce service)
    volumes:
      - ./config/ldap:/bitnami/openldap
    restart: always

  home_assistant:
    build:
      context: /home/toine-fa/SAE5.02/Dockerfile/homeassistant
    image: homeassistant/home-assistant:stable
    networks:
      internal_net:
        ipv4_address: 192.168.0.5
    container_name: home_assistant
    environment:
      - TZ=Europe/Paris
    ports:
      - 8123:8123
      - "2225:22"  # Port SSH exposé sur l'hôte (port 2225 pour ce service)
    volumes:
      - /opt/docker/ha/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always

  # Serveur VPN OpenVPN
  openvpn:
    build:
      context: /home/toine-fa/SAE5.02/Dockerfile/openvpn-as
    image: openvpn/openvpn
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    ports:
      - "943:943"
      - "8443:443"
      - "1194:1194/udp"
      - "2226:22"  # Port SSH exposé sur l'hôte (port 2226 pour ce service)
    networks:
      internal_net:
        ipv4_address: 192.168.0.6
    volumes:
      - ~/docker/openvpn-as:/openvpn
    restart: always

  # Pare-feu OPNsense
  opnsense:
    build:
      context: /home/toine-fa/SAE5.02/Dockerfile/opnsense
    image: nginx:latest
    container_name: opnsense
    networks:
      internal_net:
        ipv4_address: 192.168.0.7
    environment:
      - TZ=Europe/Paris
    ports:
      - "8080:80"
      - "2227:22"  # Port SSH exposé sur l'hôte (port 2227 pour ce service)
    volumes:
      - ./config/opnsense:/etc/nginx/conf.d
    restart: always
    command: bash -c "apt-get update && apt-get install -y openssh-server && service ssh start"

  # Machine Client
  client:
    build:
      context: /home/toine-fa/SAE5.02/Dockerfile/client
    image: debian:latest
    container_name: client
    networks:
      internal_net:
        ipv4_address: 192.168.0.8
    environment:
      - DISPLAY
    command: bash -c "apt-get update && apt-get install -y xfce4 openssh-server && service ssh start"
    ports:
      - "2228:22"  # Port SSH exposé sur l'hôte (port 2228 pour ce service)
    restart: always

networks:
  internal_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24

volumes:
  data:
