version: '3.8'

services:
  # Serveur DNS
  dns:
    image: sameersbn/bind:latest
    container_name: dns
    networks:
      internal_net:
        ipv4_address: 192.168.0.2
    environment:
      - BIND_USER=root
    ports:
      - "533:53/udp"  # Port DNS
    volumes:
      - ./config/dns:/data
    restart: always
    command: bash -c "apt-get update && apt-get install -y openssh-server && service ssh start"

  # Active Directory avec Samba
  ad:
    image: dperson/samba
    container_name: samba
    environment:
      TZ: 'Europe/Paris'  # Remplacez par le fuseau horaire approprié si nécessaire
    networks:
      default:
        ipv4_address: 192.168.0.3  # Optionnel, ajoutez une IP statique si requis
    ports:
      - "137:137/udp"  # Service NetBIOS
      - "138:138/udp"  # Service NetBIOS
      - "139:139/tcp"  # Partages SMB
      - "445:445/tcp"  # Partages SMB
    tmpfs:
      - /tmp  # Répertoire temporaire en mémoire pour des performances accrues
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /mnt:/mnt:z       # Partage du répertoire /mnt
      - /mnt2:/mnt2:z     # Partage du répertoire /mnt2
    command: >
      -s "Public;/mnt;no;no;no"         # Partage public en lecture seule
      -s "Private;/mnt2;yes;no;no;bob" # Partage privé, accessible à l'utilisateur "bob"
      -u "bob;bobspasswd"              # Déclaration de l'utilisateur "bob" avec mot de passe "bobspasswd"

  ldap_cli:
    image: dnknth/ldap-ui
    container_name: ldap_cli
    networks:
      internal_net:
        ipv4_address: 192.168.0.4
    environment:
      - LDAP_URL=ldap://ldap:1389
      - BASE_DN=dc=example,dc=org
      - BIND_PATTERN=%s
    ports:
      - "1234:5000"
    volumes:
      - ./config/ldap:/bitnami/openldap
    restart: always

  home_assistant:
    image: homeassistant/home-assistant:stable
    container_name: home_assistant
    networks:
      internal_net:
        ipv4_address: 192.168.0.5
    environment:
      - TZ=Europe/Paris
    ports:
      - "8123:8123"  # Port Home Assistant
    volumes:
      - ./config/home_assistant:/config
    restart: always
    command: bash -c "apt-get update && apt-get install -y openssh-server && service ssh start && /init"

  # Serveur VPN OpenVPN

  openvpn-as:
    image: openvpn/openvpn-as
    container_name: openvpn-as
    cap_add:
      - NET_ADMIN
    ports:
      - "943:943"          # Port pour l'interface d'administration
      - "8443:443"         # Port HTTPS
      - "1194:1194/udp"    # Port UDP pour les connexions VPN
    networks:
      internal_net:
        ipv4_address: 192.168.0.6
    volumes:
      - ~/docker/openvpn-as:/openvpn # Volume pour la persistance des données
    restart: always


  # Pare-feu OPNsense
  opnsense:
    image: nginx:latest  # Placeholder pour simuler un pare-feu avec des règles de proxy
    container_name: opnsense
    networks:
      internal_net:
        ipv4_address: 192.168.0.7
    environment:
      - TZ=Europe/Paris
    ports:
      - "8080:80"  # Port HTTP pour accéder au pare-feu simulé
    volumes:
      - ./config/opnsense:/etc/nginx/conf.d
    restart: always
    command: bash -c "apt-get update && apt-get install -y openssh-server && service ssh start"

  # Machine Client
  client:
    image: debian:latest
    container_name: client
    networks:
      internal_net:
        ipv4_address: 192.168.0.8
    environment:
      - DISPLAY
    command: bash -c "apt-get update && apt-get install -y xfce4 openssh-server && service ssh start"
    restart: always

networks:
  internal_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24
