version: '3.8'

services:
  # Serveur DNS
  dns:
    image: sameersbn/bind:latest
    container_name: dns
    networks:
      internal_net:
        ipv4_address: 192.168.0.2
    environment:
      - BIND_USER=root
    ports:
      - "533:53/udp"  # Port DNS
    volumes:
      - ./config/dns:/data
    restart: always
    command: bash -c "apt-get update && apt-get install -y openssh-server && service ssh start"

  # Active Directory avec Samba
  ad:
    image: dperson/samba
    container_name: ad
    networks:
      internal_net:
        ipv4_address: 192.168.0.3
    environment:
      - TZ=Europe/Paris
      - SAMBA_DOMAIN=domaine_toinefa
      - SAMBA_REALM=domaine.toinefa
      - SAMBA_ADMIN_PASSWORD=root
    ports:
      - "389:389"
      - "445:445"
      - "3268:3268"
    volumes:
      - ./config/ad:/etc/samba
    restart: always
    command: "/sbin/tini -- /usr/sbin/smbd -D"

  ldap:
    image: bitnami/openldap:latest
    container_name: ldap
    networks:
      internal_net:
        ipv4_address: 192.168.0.4
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_USERS=user01,user02,user03,user04,user05,user06,user07,user08,user09,user10,user11,user12,user13,user14,user15,user16,user17,user18,user19,user20,user21,user22,user23,user24,user25,user26,user27,user28,user29,user30,user31,user32,user33,user34,user35,user36,user37,user38,user39,user40,user41,user42,user43,user44,user45,user46,user47,user48,user49,user50
      - LDAP_PASSWORDS=password1,password2,password3,password4,password5,password6,password7,password8,password9,password10,password11,password12,password13,password14,password15,password16,password17,password18,password19,password20,password21,password22,password23,password24,password25,password26,password27,password28,password29,password30,password31,password32,password33,password34,password35,password36,password37,password38,password39,password40,password41,password42,password43,password44,password45,password46,password47,password48,password49,password50
      - LDAP_BASE_DN=dc=example,dc=org
    ports:
      - "1389:1389"
      - "1636:1636"
    volumes:
      - ./config/ldap:/bitnami/openldap
    restart: always

  ldap_cli:
    image: dnknth/ldap-ui
    container_name: ldap_cli
    networks:
      internal_net:
        ipv4_address: 192.168.0.5
    environment:
      - LDAP_URL=ldap://ldap:1389
      - BASE_DN=dc=example,dc=org
      - BIND_PATTERN=%s
    ports:
      - "1234:5000"
    volumes:
      - ./config/ldap:/bitnami/openldap
    restart: always

  home_assistant:
    image: homeassistant/home-assistant:stable
    container_name: home_assistant
    networks:
      internal_net:
        ipv4_address: 192.168.0.6
    environment:
      - TZ=Europe/Paris
    ports:
      - "8123:8123"  # Port Home Assistant
    volumes:
      - ./config/home_assistant:/config
    restart: always
    command: bash -c "apt-get update && apt-get install -y openssh-server && service ssh start && /init"

  # Serveur VPN OpenVPN
  openvpn:
    image: kylemanna/openvpn:latest
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    networks:
      internal_net:
        ipv4_address: 192.168.0.7
    ports:
      - "1194:1194/udp"  # Port OpenVPN
    volumes:
      - ./config/openvpn:/etc/openvpn
    environment:
      - TZ=Europe/Paris
    restart: always
    command: "ovpn_run"

  # Pare-feu OPNsense
  opnsense:
    image: nginx:latest  # Placeholder pour simuler un pare-feu avec des règles de proxy
    container_name: opnsense
    networks:
      internal_net:
        ipv4_address: 192.168.0.8
    environment:
      - TZ=Europe/Paris
    ports:
      - "8080:80"  # Port HTTP pour accéder au pare-feu simulé
    volumes:
      - ./config/opnsense:/etc/nginx/conf.d
    restart: always
    command: bash -c "apt-get update && apt-get install -y openssh-server && service ssh start"

  # Machine Client
  client:
    image: debian:latest
    container_name: client
    networks:
      internal_net:
        ipv4_address: 192.168.0.9
    environment:
      - DISPLAY
    command: bash -c "apt-get update && apt-get install -y xfce4 openssh-server && service ssh start"
    restart: always

networks:
  internal_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24
