version: '3.8'

services:
  # Serveur DNS
  dns:
    image: sameersbn/bind:latest
    container_name: dns
    networks:
      internal_net:
        ipv4_address: 192.168.0.2
    environment:
      - BIND_USER=root
    ports:
      - "533:53/udp"  # Port DNS
    volumes:
      - ./config/dns:/data
    restart: always
    # Installer SSH sur ce conteneur
    command: bash -c "apt-get update && apt-get install -y openssh-server && service ssh start"

  # Active Directory avec Samba
  ad:
    image: dperson/samba
    container_name: ad
    networks:
      internal_net:
        ipv4_address: 192.168.0.3
    environment:
      - TZ=Europe/Paris
      - SAMBA_DOMAIN=domaine_toinefa
      - SAMBA_REALM=domaine.toinefa
      - SAMBA_ADMIN_PASSWORD=root
    ports:
      - "389:389"
      - "445:445"
      - "3268:3268"
    volumes:
      - ./config/ad:/etc/samba
    restart: always
    command: "/sbin/tini -- /usr/sbin/smbd -D"


  ldap:
    image: osixia/openldap:latest
    container_name: ldap
    networks:
      internal_net:
        ipv4_address: 192.168.0.4
    environment:
      - LDAP_ORGANISATION="Mon Organisation"
      - LDAP_DOMAIN="domaine.local"
      - LDAP_ADMIN_PASSWORD=admin_password
    ports:
      - "3389:389"
      - "636:636"
    volumes:
      - ./config/ldap:/var/lib/ldap
      - ./config/slapd.d:/etc/ldap/slapd.d
    restart: always
    # Ajouter SSH sur ce conteneur
    command: bash -c "apt-get update && apt-get install -y openssh-server && service ssh start &&  /container/tool/run"

  home_assistant:
    image: homeassistant/home-assistant:stable
    container_name: home_assistant
    networks:
      internal_net:
        ipv4_address: 192.168.0.5
    environment:
      - TZ=Europe/Paris
    ports:
      - "8123:8123"  # Port Home Assistant
    volumes:
      - ./config/home_assistant:/config
    restart: always
    command: bash -c "apt-get update && apt-get install -y openssh-server && service ssh start && /init"


  # Serveur VPN OpenVPN
  openvpn:
    image: kylemanna/openvpn:latest
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    networks:
      internal_net:
        ipv4_address: 192.168.0.6
    ports:
      - "1194:1194/udp"  # Port OpenVPN
    volumes:
      - ./config/openvpn:/etc/openvpn
    environment:
      - TZ=Europe/Paris
    restart: always
    command: "ovpn_run"

  # Pare-feu OPNsense
  opnsense:
    image: nginx:latest  # Placeholder pour simuler un pare-feu avec des règles de proxy
    container_name: opnsense
    networks:
      internal_net:
        ipv4_address: 192.168.0.7
    environment:
      - TZ=Europe/Paris
    ports:
      - "8080:80"  # Port HTTP pour accéder au pare-feu simulé
    volumes:
      - ./config/opnsense:/etc/nginx/conf.d
    restart: always
    # Ajouter SSH sur ce conteneur
    command: bash -c "apt-get update && apt-get install -y openssh-server && service ssh start"

  # Machine Client
  client:
    image: debian:latest
    container_name: client
    networks:
      internal_net:
        ipv4_address: 192.168.0.8
    environment:
      - DISPLAY
    command: bash -c "apt-get update && apt-get install -y xfce4 openssh-server && service ssh start "
    restart: always

networks:
  internal_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24
