version: '3.8'

services:
  # Serveur DNS avec Bind9
  dns:
    image: ubuntu:20.04  # Image Ubuntu Server
    container_name: dns
    networks:
      internal_net:
        ipv4_address: 192.168.0.2
    ports:
      - "5443:5443/udp"   # Port DNS UDP
      - "5553:5553/tcp"   # Port DNS TCP
      - "10000:10000/tcp" # Port d'administration
      - "2222:22"         # Port SSH exposé sur l'hôte
    volumes:
      - ./bind:/etc/bind
      - ./keys:/etc/bind/keys
    environment:
      - DEBIAN_FRONTEND=noninteractive
    command: bash -c "apt-get update && apt-get install -y bind9 bind9utils openssh-server && \
                      service ssh start && named -f"
    restart: always

  # Active Directory (Samba)
  ad:
    image: ubuntu:20.04  # Image Ubuntu Server
    container_name: ad
    networks:
      internal_net:
        ipv4_address: 192.168.0.3
    ports:
      - "2223:22"  # Port SSH exposé sur l'hôte
    volumes:
      - ./smb:/etc/samba
    environment:
      - DEBIAN_FRONTEND=noninteractive
    command: bash -c "apt-get update && apt-get install -y samba openssh-server && \
                      service ssh start && service smbd start"
    restart: always

  # Serveur LDAP
  ldap:
    image: ubuntu:20.04  # Image Ubuntu Server
    container_name: ldap
    networks:
      internal_net:
        ipv4_address: 192.168.0.4
    ports:
      - "1389:389"  # Port LDAP
      - "2224:22"   # Port SSH exposé sur l'hôte
    volumes:
      - ./ldap_data:/var/lib/ldap
      - ./ldap_config:/etc/ldap/slapd.d
    environment:
      - DEBIAN_FRONTEND=noninteractive
    command: bash -c "apt-get update && apt-get install -y slapd ldap-utils openssh-server && \
                      service ssh start && service slapd start"
    restart: always

  # Home Assistant
  home_assistant:
    image: ubuntu:20.04  # Image Ubuntu Server
    container_name: home_assistant
    networks:
      internal_net:
        ipv4_address: 192.168.0.5
    ports:
      - "8123:8123"  # Interface Web Home Assistant
      - "2225:22"    # Port SSH exposé sur l'hôte
    volumes:
      - ./homeassistant:/config
    environment:
      - DEBIAN_FRONTEND=noninteractive
    command: bash -c "apt-get update && apt-get install -y openssh-server && \
                      service ssh start && python3 -m homeassistant --config /config"
    restart: always

  # Serveur OpenVPN
  openvpn:
    image: ubuntu:20.04  # Image Ubuntu Server
    container_name: openvpn
    networks:
      internal_net:
        ipv4_address: 192.168.0.6
    ports:
      - "1194:1194/udp"  # Port VPN UDP
      - "2226:22"        # Port SSH exposé sur l'hôte
    volumes:
      - ./openvpn:/etc/openvpn
    environment:
      - DEBIAN_FRONTEND=noninteractive
    command: bash -c "apt-get update && apt-get install -y openvpn openssh-server && \
                      service ssh start"
    restart: always

  # Pare-feu OPNsense (simulé)
  opnsense:
    image: ubuntu:20.04  # Image Ubuntu Server
    container_name: opnsense
    networks:
      internal_net:
        ipv4_address: 192.168.0.7
    ports:
      - "8080:80"    # Interface Web pour simulation
      - "2227:22"    # Port SSH exposé sur l'hôte
    volumes:
      - ./opnsense_config:/etc/nginx/conf.d
    environment:
      - DEBIAN_FRONTEND=noninteractive
    command: bash -c "apt-get update && apt-get install -y nginx openssh-server && \
                      service ssh start && nginx -g 'daemon off;'"
    restart: always

  # Machine Client
  client:
    image: ubuntu:20.04  # Image Ubuntu Server
    container_name: client
    networks:
      internal_net:
        ipv4_address: 192.168.0.8
    ports:
      - "2228:22"  # Port SSH exposé sur l'hôte
    environment:
      - DISPLAY
    command: bash -c "apt-get update && apt-get install -y xfce4 openssh-server && \
                      service ssh start"
    restart: always

networks:
  internal_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24

volumes:
  bind:
  keys:
  smb:
  ldap_data:
  ldap_config:
  homeassistant:
  openvpn:
  opnsense_config:
