version: '3.8'

services:
  # Serveur DNS
  dns:
    image: sameersbn/bind:latest
    container_name: dns
    networks:
      internal_net:
        ipv4_address: 192.168.0.2
    environment:
      - BIND_USER=root
    ports:
      - "533:53/udp"  # Port DNS
    volumes:
      - ./config/dns:/data
    restart: always
    command: bash -c "apt-get update && apt-get install -y openssh-server && service ssh start"

  # Active Directory avec Samba
  samba:
    image: crazymax/samba
    networks:
      internal_net:
        ipv4_address: 192.168.0.3
    container_name: samba
    volumes:
      - ./smb:/data
      - ./downloads:/downloads
    environment:
      - "TZ=$TIMEZONE"
      - "SAMBA_LOG_LEVEL=0"
    restart: always


  ldap_cli:
    image: dnknth/ldap-ui
    container_name: ldap_cli
    networks:
      internal_net:
        ipv4_address: 192.168.0.4
    environment:
      - LDAP_URL=ldap://ldap:1389
      - BASE_DN=dc=example,dc=org
      - BIND_PATTERN=%s
    ports:
      - "1234:5000"
    volumes:
      - ./config/ldap:/bitnami/openldap
    restart: always

  homeassistant:
    image: homeassistant/home-assistant:stable
    networks:
      internal_net:
        ipv4_address: 192.168.0.5
    container_name: homeassistant
    environment:
      - TZ=Europe/Paris
    ports:
      - 8123:8123
    volumes:
      - /opt/docker/ha/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always

  # Serveur VPN OpenVPN

  openvpn-as:
    image: openvpn/openvpn-as
    container_name: openvpn-as
    cap_add:
      - NET_ADMIN
    ports:
      - "943:943"          # Port pour l'interface d'administration
      - "8443:443"         # Port HTTPS
      - "1194:1194/udp"    # Port UDP pour les connexions VPN
    networks:
      internal_net:
        ipv4_address: 192.168.0.6
    volumes:
      - ~/docker/openvpn-as:/openvpn # Volume pour la persistance des données
    restart: always


  # Pare-feu OPNsense
  opnsense:
    image: nginx:latest  # Placeholder pour simuler un pare-feu avec des règles de proxy
    container_name: opnsense
    networks:
      internal_net:
        ipv4_address: 192.168.0.7
    environment:
      - TZ=Europe/Paris
    ports:
      - "8080:80"  # Port HTTP pour accéder au pare-feu simulé
    volumes:
      - ./config/opnsense:/etc/nginx/conf.d
    restart: always
    command: bash -c "apt-get update && apt-get install -y openssh-server && service ssh start"

  # Machine Client
  client:
    image: debian:latest
    container_name: client
    networks:
      internal_net:
        ipv4_address: 192.168.0.8
    environment:
      - DISPLAY
    command: bash -c "apt-get update && apt-get install -y xfce4 openssh-server && service ssh start"
    restart: always

networks:
  internal_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24
