version: '3.8'

services:
  ad:
    build:
      context: .
    container_name: ad
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "389:389"
      - "88:88"
      - "464:464"
      - "445:445"
      - "2223:22"
    environment:
      TZ: "Europe/Paris"
    networks:
      shared_net:
        ipv4_address: 192.168.0.3
    volumes:
      - ./smb.conf:/etc/samba/smb.conf
      - ./krb5.conf:/etc/krb5.conf

volumes:
  samba_data:
    driver: local                  # Volume pour stocker les données persistantes de Samba
  samba_krb:
    driver: local                  # Volume pour stocker les données persistantes de Kerberos

networks:
  shared_net:
    name: shared_net               # Réseau partagé avec Bind9
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24   # Sous-réseau commun
