# docker-compose.yml

version: '3.8'

services:
  ad:
    build:
      context: .  # Le dossier avec le Dockerfile
    container_name: ad
    environment:
      TZ: "Europe/Paris"
    networks:
      shared_net:
        ipv4_address: 192.168.0.3
    ports:
      - "2223:22"  # Port SSH exposé sur l'hôte
      - "88:88"
      - "389:389"
    volumes:
      - ./smb:/etc/samba

# networks:
#   shared_net:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 192.168.0.0/24  # Sous-réseau commun
