- name: Déployer Samba AD avec Docker et Ansible
  hosts: docker_host
  become: true
  tasks:
    - name: Installer Docker et Docker Compose si nécessaire
      apt:
        name:
          #- docker.io
          #- docker-compose
        state: present
        update_cache: yes

    - name: Créer le répertoire de destination pour Samba
      file:
        path: /root/test_ansible/roles/samba
        state: directory
        mode: '0755'

    - name: Copier le fichier docker-compose.yml pour Samba
      copy:
        src: /home/toine-fa/SAE5.02/test_ansible/roles/samba/docker-compose.yml
        dest: /root/test_ansible/roles/samba/docker-compose.yml

    - name: Copier le fichier Dockerfile pour Samba
      copy:
        src: /home/toine-fa/SAE5.02/test_ansible/roles/samba/Dockerfile
        dest: /root/test_ansible/roles/samba/Dockerfile

    - name: Copier le fichier smb.conf pour Samba
      copy:
        src: /home/toine-fa/SAE5.02/test_ansible/roles/samba/smb.conf
        dest: /root/test_ansible/roles/samba/smb.conf

    - name: Copier le fichier krb5.conf pour Samba
      copy:
        src: /home/toine-fa/SAE5.02/test_ansible/roles/samba/krb5.conf
        dest: /root/test_ansible/roles/samba/krb5.conf

    - name: Lancer Samba AD avec Docker Compose
      command: docker-compose -f /root/test_ansible/roles/samba/docker-compose.yml up -d


- name: Configurer Samba dans le conteneur
  hosts: ad
  become: true
  vars_files:
    - roles/samba/vars/main.yml
  tasks:
    - include_tasks: tasks/main.yml
