version: "3.9"

services:
  bind9:
    image: debian:latest
    container_name: bind9
    hostname: bind9
    #volumes:
      #- bind-config:/etc/bind
      #- bind-cache:/var/cache/bind
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "2222:22"  # SSH exposé
    command: ["tail", "-f", "/dev/null"]  # Garder le conteneur actif sans exiger sshd
    networks:
      - internal_net

volumes:
  bind-config:
    driver: local