version: '3.9'

services:
  bind9:
    image: internetsystemsconsortium/bind9:latest  # Utiliser la version 'latest' ou une autre version valide
    container_name: bind9
    networks:
      - bind_network
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    restart: always

networks:
  bind_network:
    driver: bridge
