version: '3.7'

services:
  bind9:
    image: internetsystemsconsortium/bind9:9.16
    container_name: bind9
    networks:
      - internal_net  # Référence au réseau défini ci-dessous
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    restart: always

networks:
  internal_net:  # Définition du réseau "internal_net"
    driver: bridge
