---
- name: Installer les paquets un par un
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - samba
    # - smbclient
    # - krb5-user
    # - bind9utils
    # - dnsutils
    - openssh-server
  environment:
    DEBIAN_FRONTEND: noninteractive


- name: Configurer le fichier krb5.conf
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    mode: '0644'

- name: Provisionner le domaine Samba AD
  command: >
    samba-tool domain provision
    --use-rfc2307
    --realm={{ realm }}
    --domain={{ domain }}
    --server-role=dc
    --dns-backend=BIND9_DLZ
    --adminpass={{ admin_password }}
  args:
    creates: /etc/samba/smb.conf

- name: Démarrer Samba
  service:
    name: samba
    state: started
    enabled: yes
