FROM ubuntu:20.04

# Mettre à jour le système et installer les dépendances de base
RUN apt-get update && apt-get install -y --no-install-recommends \
    openssh-server \
    python3 \
    python3-pip \
    curl \
    sudo \
    nano \
    dnsutils \
    iputils-ping && \
    apt-get clean && \
    pip install hass-nabucasa &&\
    pip install --upgrade cryptography pyopenssl &&\
    pip install --upgrade boto3 botocore &&\
    rm -rf /var/lib/apt/lists/*

# Configurer SSH
RUN mkdir /var/run/sshd && \
    echo 'root:root' | chpasswd && \
    sed -i 's/#Port 22/Port 22/' /etc/ssh/sshd_config && \
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# Exposer les ports
EXPOSE 22 8123

# Commande de démarrage
CMD service ssh start && tail -f /dev/null
