- name: Afficher les variables chargées
  debug:
    var: Zone_A

- name: Installer Bind9
  apt:
    name:
      - bind9
      - bind9utils
      - bind9-doc
      - openssh-server
    state: present
    update_cache: yes

- name: Charger les variables pour Bind9
  include_vars: vars/main.yml

- name: Copier la configuration principale de Bind9
  template:
    src: templates/named.conf.j2
    dest: /etc/bind/named.conf
    owner: root
    group: bind
    mode: '0644'
    unsafe_writes: true
  become: true

- name: Copier les fichiers de zones DNS
  template:
    src: db.Zone_A.j2
    dest: /etc/bind/db.{{ bind_zone_name }}

- name: Vérifier la validité des fichiers de configuration
  command: named-checkconf /etc/bind/named.conf

- name: Vérifier la validité des fichiers de zone
  command: named-checkzone {{ bind_zone_name }} /etc/bind/db.{{ bind_zone_name }}

- name: Redémarrer le conteneur Docker contenant Bind9
  docker_container:
    name: bind9
    state: restarted

#- name: Démarrer ou redémarrer Bind9
  # service:
    # use : "service"
    # name: named
    # state: restarted
