---
# Toutes les tâches pour configurer Bind9
- name: Installer Bind9
  apt:
    name: bind9
    state: present
    update_cache: yes

- name: Copier la configuration Bind9
  template:
    src: named.conf.j2
    dest: /etc/bind/named.conf

- name: Copier les fichiers de zone
  template:
    src: db.example.com.j2
    dest: /etc/bind/db.example.com

- name: Redémarrer Bind9
  service:
    name: bind9
    state: restarted

- name: Installer SSH et Bind9
  apt:
    name:
      - bind9
      - openssh-server
    state: present
    update_cache: yes

- name: Configurer SSH pour root
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin yes'

- name: Démarrer le serveur SSH
  command: service ssh start
